/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Bridge */

#ifndef _Included_jni_Bridge
#define _Included_jni_Bridge
#ifdef __cplusplus
extern "C"
{
#endif
  /*
   * Class:     jni_Bridge
   * Method:    initializeBridge
   * Signature: ()V
   */
  JNIEXPORT void JNICALL Java_jni_Bridge_initializeBridge(JNIEnv *, jclass);

  /*
   * Class:     jni_Bridge
   * Method:    startChatRoom
   * Signature: (Ljava/lang/String;)V
   */
  JNIEXPORT jint JNICALL Java_jni_Bridge_startChatRoom(JNIEnv *, jclass, jstring);

  /*
   * Class:     jni_Bridge
   * Method:    joinChatRoom
   * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
   */
  JNIEXPORT void JNICALL Java_jni_Bridge_joinChatRoom(JNIEnv *, jclass, jstring, jstring, jstring, jstring);

  /*
   * Class:     jni_Bridge
   * Method:    sendMessage
   * Signature: (Ljava/lang/String;)V
   */
  JNIEXPORT void JNICALL Java_jni_Bridge_sendMessage(JNIEnv *, jclass, jstring);

  /*
   * Class:     jni_Bridge
   * Method:    kickUser
   * Signature: (Ljava/lang/String;)V
   */
  JNIEXPORT void JNICALL Java_jni_Bridge_kickUser(JNIEnv *, jclass, jstring);

  /*
   * Class:     jni_Bridge
   * Method:    banUser
   * Signature: (Ljava/lang/String;)V
   */
  JNIEXPORT void JNICALL Java_jni_Bridge_banUser(JNIEnv *, jclass, jstring);

  /*
   * Class:     jni_Bridge
   * Method:    leaveChatRoom
   * Signature: ()V
   */
  JNIEXPORT void JNICALL Java_jni_Bridge_leaveChatRoom(JNIEnv *, jclass);

  /*
   * Class:     jni_Bridge
   * Method:    closeChatRoom
   * Signature: ()V
   */
  JNIEXPORT void JNICALL Java_jni_Bridge_closeChatRoom(JNIEnv *, jclass);

  void callback_error(const char *aggregated_message, int max_severity);
  void callback_message(const char *message, const char *username);
  void callback_server_error(error_type_t error_type, const char *message);
  void callback_notification(notification_type_t notification_type, const char *message);

#ifdef __cplusplus
}
#endif
#endif
